### ISSUE TITLE
Test connection to tenant failed 

### ISSUE THREAD

**Issue by Getoffmypatch** [Yvand/EntraCP#231]
I have deployed the solution and updated the trusted provider but when I click the troubleshooting page I get the message below for connection to the tenant. 

Test connection to tenant 'ReplaceWithYourOwnValue' failed due to invalid credentials: ClientSecretCredential authentication failed: AADSTS900023: Specified tenant identifier 'replacewithyourownvalue' is neither a valid DNS name, nor a valid external domain. 

I dont see where I should have updated the tenant somewhere other than the scripts here - https://entracp.yvand.net/docs/configuration/

Please note that I have previously installed AzureCP on the same farm but have not yet removed that solution.

If I have missed a step, please advise.

Thanks,
Shane

**Comment by Yvand** [comment]
@Getoffmypatch it is perfectly normal: This page is standalone and independent of the actual config, to help you troubleshoot EntraCP when needed.
For this reason, this `ReplaceWithYourOwnValue` is hardcoded in the .aspx page itself and you need to edit it manually.

You are not the 1st one to be confused by this page, I need to make it more explicit that it is the expected behavior.

**Comment by Getoffmypatch** [comment]
Thanks - where is the page that I can edit? Also, my user lookup isnt working now, so something is still missing if you can provide some guidance?

**Comment by Getoffmypatch** [comment]
I updated the page and it work fine now. Thanks
