### ISSUE TITLE
People Picker not showing results and unable to update claim mappings.

### ISSUE THREAD

**Issue by jaycallahan1973** [Yvand/EntraCP#237]
Building a new farm and old farm was using AzureCP.  I was doing comparison and noticed my Claim Type was different in the new farm.  When I try to edit it I don't get anything. I saw this same issue in earlier post but it looked like it was resolved.  Is there something else I need to be checking?

![image](https://github.com/Yvand/EntraCP/assets/51999317/df31e7c3-cae0-406d-b6b7-5faf18c43842)

**Comment by Yvand** [comment]
@jaycallahan1973 one thing to understand: EntraCP does not decide what claim types to use, it reads them from the trust it is associated with ("azuread" based on your screenshot).
It is expected that you cannot change the identity claim type in this page, since it is not set/decided by EntraCP, it is configured in the trust directly
