### ISSUE TITLE
Deployment Status Question

### ISSUE THREAD

**Issue by Getoffmypatch** [Yvand/EntraCP#239]
Hello Yvan,

Whilst deploying to a different environment I have come across the following where the status of the solution is shown as "Not Deployed". In the solution properties below, it shows as not deployed but also successfully deployed.

![image](https://github.com/Yvand/EntraCP/assets/32172026/1b2612d0-cc76-4ae3-bc69-ee06af86dd82)

The questions is if its fully deployed or not? The solution exists in Central Admin and I was able to add the connection to the tenant.

Thanks,
Shane

**Comment by Yvand** [comment]
@Getoffmypatch, yes, this is one of the weird ramdon behavior of SharePoint with solution deployments.
It could be that somehow it did not deploy on a specific server, or something you can simply ignore.
But if you still have the button to deploy the solution, you can click on it and let SharePoint redeploy the bits and update its status. This operation is safe with EntraCP because it does not do any feature activation in this step,

**Comment by Getoffmypatch** [comment]
Hi Yvan - Using the deploy button attempts the deployment again but ultimately returns to the same status

**Comment by Getoffmypatch** [comment]
Hi Yvan. I found the problem. The deployment was failing to one of the servers in the farm due to issues with the SecurityTokenService on that server. After various attempts to fix, I removed and readded the server to the farm and now the deployment status is correct and the token service is running as expected.
